server:
 port: 8080
 servlet:
   context-path: /indentity

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "MH6XaEf51MJBLZXwGglkMQDVfSArLgBw3Jj5L/VTnIhFfURT420DApXKd5ceN28D"