server:
 port: 8080
 servlet:
   context-path: /indentity

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ${JWT_SIGNERKEY}
  valid-duration: 60
  refreshable-duration: 120